reviewers:
  # The default reviewers
  defaults:
    - repository-owners # group
    
  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    repository-owners:
      - team:owners # GitHub team

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
